import json
import os

pt_path = r"C:\Users\milto\Documents\ai-saas\messages\pt.json"
en_path = r"C:\Users\milto\Documents\ai-saas\messages\en.json"

mentoring_profile_pt = {
  "title": "Meu Perfil de Mentoria",
  "subtitleEdit": "Configurando Detalhes do Perfil",
  "subtitleView": "Visualização de evolução e trajetória",
  "levelPrefix": "LV",
  "xp": "XP",
  "noName": "Sem Nome Definido",
  "roleMentor": "Mentor",
  "roleMentee": "Mentorado",
  "noTagline": "Tagline não especificada",
  "mentorExec": "Mentor Executivo",
  "bizEstrategista": "Estrategista de Negócios",
  "specTooltipTitle": "Especialidade",
  "specTooltipDesc": "Calculado dinamicamente a partir dos seus objetivos, trajetória profissional e competências.",
  "menteesCount": "Mentorados: {count}",
  "levelLabel": "Nível: {level}",
  "focusLabel": "Foco: {focus}",
  "focusTooltipTitle": "Índice de Foco",
  "focusTooltipDesc": "Métrica de foco diário (Esforço Mental / Tempo Dedicado) calculada dos seus diários de bordo recentes.",
  "tasksLabel": "Tarefas: {completed}/{total}",
  "tasksTooltipTitle": "Tarefas Executadas",
  "tasksTooltipDesc": "Seu progresso de atividades concluídas no quadro Kanban operacional.",
  "nextSession": "Próxima Sessão: {date}",
  "noSession": "Sem sessão agendada",
  "publicLink": "Link Público",
  "motivationalQuotePlaceholder": "Defina sua frase de efeito ou citação nas configurações do perfil para exibi-la aqui.",
  "achievements": {
    "consistent": {
      "title": "Foco Consistente",
      "desc": "Mais de 75% de engajamento em tarefas ativas."
    },
    "implacavel": {
      "title": "Implacável",
      "desc": "Completou pelo menos 5 tarefas no workspace."
    },
    "resiliente": {
      "title": "Operador Resiliente",
      "desc": "Escreveu seu primeiro relatório no Diário de Bordo."
    },
    "visionario": {
      "title": "Líder Visionário",
      "desc": "Estruturou sua visão de futuro nas configurações."
    },
    "unlocked": "Desbloqueado",
    "locked": "Bloqueado"
  },
  "social": {
    "linkedin": "LinkedIn",
    "github": "GitHub",
    "instagram": "Instagram",
    "website": "Website",
    "whatsapp": "WhatsApp"
  },
  "tabs": {
    "dashboard": "Painel de Evolução",
    "diary": "Diário de Bordo",
    "tasks": "Tarefas (Kanban)",
    "schedule": "Agenda Sessões",
    "mentorPanel": "Painel do Mentor",
    "config": "Configurações",
    "secretary": "Secretaria IA"
  },
  "secReportHeader": "Secretaria IA (I/O) • Relatório de Evolução",
  "secReportSubtitle": "Diretrizes estratégicas e próximos passos operacionais",
  "viewHistory": "Ver Histórico",
  "reportTitle": "📄 Relatório de Evolução",
  "createdAt": "Criado em: {date}",
  "collapseReport": "↑ recolher relatório",
  "expandReport": "↓ clique para expandir relatório completo",
  "noReportGenerated": "Nenhum relatório de evolução gerado para este ciclo.",
  "compiling": "Compilando...",
  "generateReport": "Gerar Relatório de Evolução",
  "guideTitle": "Diretrizes & Alinhamento de Evolução",
  "guideSubtitle": "Seu planejamento estratégico pessoal e alinhamento de propósito na mentoria",
  "expectationLabel": "Expectativas da Mentoria",
  "notFilled": "Não preenchido nas configurações.",
  "shortTermLabel": "Objetivos de Curto Prazo",
  "mediumTermLabel": "Objetivos de Médio Prazo",
  "professionalDreamLabel": "Sonho Profissional (Estrela Guia)",
  "hobbiesLabel": "Hobbies, Artes & Talentos",
  "bioTrajectoryLabel": "Biografia & Trajetória",
  "noBio": "Nenhuma biografia disponível.",
  "experienceLabel": "Experiência Profissional",
  "noExperience": "Histórico de experiência não preenchido.",
  "skillsLabel": "Habilidades & Competências",
  "noSkills": "Nenhuma competência cadastrada.",
  "personalGoalLabel": "Objetivo Pessoal",
  "notDefined": "Não definido.",
  "careerGoalLabel": "Objetivo de Carreira",
  "personalAttributesLabel": "3 Atributos Pessoais",
  "notFilledShort": "Não preenchido",
  "greatestAchievementsLabel": "3 Grandes Conquistas",
  "greatestQualityLabel": "Maior Qualidade",
  "howOthersSeeMe": "Como os outros me veem",
  "greatestQualityPlaceholder": "Não especificado",
  "diary": {
    "newEntry": "Nova Entrada do Diário",
    "xpNote": "Registre suas métricas cognitivas e aprendizados do dia (+200 XP)",
    "mentalEffort": "Esforço Mental / Foco: {cc} / 10",
    "ccTranquil": "Tranquilo",
    "ccOverload": "Sobrecarga",
    "timeDedicated": "Tempo Dedicado / Foco: {te} / 10",
    "teFast": "Muito Rápido",
    "teSlow": "Demorado",
    "realProgress": "Progresso Real: {progress}%",
    "progressStopped": "Parado",
    "progressCompleted": "100% Concluído",
    "notesLabel": "Anotações & Relato de Aprendizados",
    "notesPlaceholder": "Quais foram seus desafios hoje? O que você aprendeu ou realizou?",
    "formulaTension": "Fórmula de Tensão: TC = CC / TE | Fórmula de Distorção: D = TC / (Progress %)",
    "writeNotesWarning": "Escreva algo nas anotações antes de registrar seu {termDiary}!",
    "registerEntry": "Registrar Entrada",
    "diaryRegistered": "{termDiary} registrado! +{xp} XP recebidos!",
    "historyTitle": "Histórico de Diários",
    "historySubtitle": "Acompanhe sua carga diária e distorções cognitivas",
    "noEntriesYet": "Nenhuma anotação registrada até o momento.",
    "tensionLabel": "Tensão",
    "distortionLabel": "Distorção",
    "flowHigh": "Fluxo Alto",
    "flowBalanced": "Equilibrado",
    "flowBurnoutRisk": "Risco Burnout"
  },
  "projects": {
    "title": "Projetos Profissionais",
    "subtitle": "Apresente e gerencie seus portfólios, startups e cases de sucesso na mentoria",
    "newProject": "Novo Projeto",
    "editProject": "Editar Projeto",
    "addProject": "Cadastrar Novo Projeto",
    "deleteConfirm": "Deseja realmente excluir este projeto?",
    "deletedSuccess": "Projeto excluído com sucesso!",
    "savedSuccess": "Projeto atualizado com sucesso!",
    "addedSuccess": "Novo projeto adicionado com sucesso!",
    "featuredUpdated": "Status de destaque do projeto atualizado com sucesso!",
    "removeFeatured": "Remover dos Destaques",
    "featurePublic": "Destacar na Vitrine Pública",
    "uploadSuccess": "Imagem do projeto carregada com sucesso!",
    "uploadError": "Erro ao fazer upload da imagem",
    "projectTitleLabel": "Título do Projeto",
    "projectTitlePlaceholder": "Ex: App de Telemedicina, MVP de Finanças",
    "tagsLabel": "Tags / Tecnologias (separadas por vírgula)",
    "tagsPlaceholder": "Ex: NextJS, React Native, SaaS",
    "descLabel": "Descrição Detalhada",
    "descPlaceholder": "Explique o objetivo do projeto, tecnologia e os resultados alcançados...",
    "imgLabel": "Imagem do Case / Logotipo (URL ou Upload)",
    "imgPlaceholder": "Cole a URL da imagem ou use o botão à direita",
    "uploadBtn": "Fazer Upload",
    "removeBtn": "Remover",
    "cancelBtn": "Cancelar",
    "saveBtn": "Salvar Alterações",
    "addBtn": "Adicionar Projeto",
    "emptyTitle": "Nenhum projeto cadastrado",
    "emptySubtitle": "Registre seus principais casos de sucesso profissionais ou de estudos",
    "addFirstProject": "Adicionar Primeiro Projeto"
  },
  "mentorControls": {
    "nomenclaturasTitle": "Nomenclaturas Chaves",
    "nomenclaturasSubtitle": "Personalize os termos chaves usados em toda a jornada do mentorado",
    "termDiaryLabel": "Termo Diário de Bordo",
    "termTensionLabel": "Termo Tensão Cognitiva",
    "termDistortionLabel": "Termo Distorção Cognitiva",
    "termSidequestLabel": "Termo Side-quest",
    "algoXpTitle": "Configurações do Algoritmo & XP",
    "algoXpSubtitle": "Ajuste os limiares de burnout e os multiplicadores de experiência da mentoria",
    "xpTaskLabel": "XP por Tarefa: {value}",
    "xpDiaryLabel": "XP por Registro: {value}",
    "xpSessionLabel": "XP por Sessão: {value}",
    "burnoutLimitLabel": "Limiar Burnout: {value}",
    "templatesTitle": "Gerenciador de Templates de Sessão",
    "templatesSubtitle": "Adicione modelos de sessões e agendas rápidas para seus alunos",
    "createNewTemplate": "Criar Novo Template",
    "templateTitleLabel": "Título da Sessão",
    "templateTitlePlaceholder": "Ex: Planejamento Trimestral",
    "templateDurationLabel": "Duração (Minutos)",
    "templateDescLabel": "Descrição/Foco",
    "templateDescPlaceholder": "Foco da mentoria e tópicos a abordar...",
    "templateAddBtn": "Adicionar Modelo",
    "templatesSavedTitle": "Modelos de Sessão Salvos",
    "deleteTemplate": "Excluir Template",
    "fillTemplateWarning": "Preencha pelo menos o título do template!",
    "templateAddedToast": "Template de Sessão adicionado!",
    "templateDeletedToast": "Template de Sessão excluído!"
  },
  "edit": {
    "realLinkedinImportTitle": "Importador LinkedIn Real",
    "realLinkedinImportDesc": "Preencha sua biografia e trajetórias automaticamente a partir do seu LinkedIn público",
    "realLinkedinBtn": "Importar do LinkedIn Real",
    "realLinkedinConnecting": "Conectando...",
    "realLinkedinExtracting": "Extraindo...",
    "realLinkedinPopulating": "Populando...",
    "realLinkedinImported": "Importado!",
    "cancelBtn": "Cancelar",
    "cancelSuccessToast": "Importação cancelada com sucesso.",
    "generalInfoTitle": "Informações Gerais",
    "roleLabel": "Papel na Mentoria",
    "roleMentor": "Mentor",
    "roleMentee": "Mentorado",
    "fullNameLabel": "Nome Completo",
    "fullNamePlaceholder": "Seu nome",
    "usernameLabel": "Username / Slug do Perfil Público",
    "usernamePlaceholder": "seu-username",
    "usernameRules": "Apenas letras minúsculas, números e hífens. Ex: milton-bolonha",
    "photoLabel": "Foto de Perfil (Cloudinary Upload / URL)",
    "photoUploading": "Enviando...",
    "photoUploadBtn": "Upload",
    "taglineLabel": "Tagline de Chamada",
    "taglinePlaceholder": "Ex: CEO na 21 Miles | Desenvolvedor Upwork",
    "genderLabel": "Gênero / Tratamento do Perfil",
    "genderMaleOption": "Masculino (Mentorado)",
    "genderFemaleOption": "Feminino (Mentorada)",
    "genderNeutralOption": "Neutro (Mentoradx)",
    "linkedinLinkLabel": "Link LinkedIn",
    "motivationalLabel": "Frase Motivacional",
    "motivationalPlaceholder": "Uma frase curta que te inspire...",
    "contactsTitle": "Contatos & Redes Sociais",
    "phoneLabel": "Telefone / Fixo",
    "phonePlaceholder": "Ex: (11) 99999-9999",
    "whatsappLabel": "WhatsApp (Número Limpo)",
    "whatsappPlaceholder": "Ex: 5511999999999",
    "emailLabel": "E-mail Profissional",
    "emailPlaceholder": "Ex: milton@21miles.com.br",
    "githubLabel": "GitHub Link",
    "instagramLabel": "Instagram Link",
    "websiteLabel": "Website / Portfolio Link",
    "mentorInfoTitle": "Informações de Mentor",
    "mentorBioLabel": "Biografia Profissional",
    "mentorBioPlaceholder": "Descreva sua jornada, liderança profissional e foco...",
    "mentorExperienceLabel": "Histórico de Experiência / Conquistas de Carreira",
    "mentorExperiencePlaceholder": "Quais foram seus maiores cargos, empresas fundadas ou tempo no mercado...",
    "skillsLabel": "Skills / Habilidades",
    "skillsPlaceholder": "Adicionar skill...",
    "addBtn": "Adicionar",
    "clickToRemove": "Clique para remover",
    "menteeInfoTitle": "Informações de Mentorado",
    "personalGoalLabel": "Objetivo Pessoal",
    "personalGoalPlaceholder": "Ex: Ter mais inteligência emocional, foco familiar ou equilíbrio...",
    "careerGoalLabel": "Objetivo de Carreira",
    "careerGoalPlaceholder": "Ex: Transição de carreira para Tech Leader, fundar minha própria startup...",
    "personalAttributesLabel": "3 Atributos que se destaca em si",
    "attributePlaceholder": "Atributo {num}",
    "experiencesLabel": "3 Experiências de sucesso na vida (Geral/Conquistas)",
    "experiencePlaceholder": "Conquista {num}",
    "futureVisionLabel": "Como se vê no futuro (Visão de Médio/Longo prazo)",
    "futureVisionPlaceholder": "Descreva seus sonhos e onde se vê nos próximos anos...",
    "greatestAttributeLabel": "Maior Atributo / Qualidade Pessoal",
    "greatestAttributePlaceholder": "Se as pessoas pudessem descrever você em um único atributo forte, qual seria?",
    "familyGroupLabel": "Grupo Familiar (Descreva brevemente)",
    "familyGroupPlaceholder": "Ex: Casado, 2 filhos, convivência próxima com os pais...",
    "hobbiesLabel": "Hobbies, Talentos & Habilidades Artísticas",
    "hobbiesPlaceholder": "Ex: Pintura digital, tocar violão clássico, jogar tênis...",
    "expectationsTitle": "Diretrizes & Alinhamento de Evolução",
    "expectationsSubtitle": "Defina suas metas estratégicas, sonhos e alinhamento profissional na mentoria",
    "expectationsLabel": "O que espera da mentoria (Expectativas)",
    "expectationsPlaceholder": "Ex: Alinhamento metodológico prático, feedbacks francos, network estratégico...",
    "shortTermGoalsLabel": "Objetivos a Curto Prazo (Foco Imediato)",
    "shortTermGoalsPlaceholder": "Ex: Concluir MVP da nova plataforma em 3 meses, organizar cronograma semanal...",
    "mediumTermGoalsLabel": "Objetivos a Médio Prazo (Construção)",
    "mediumTermGoalsPlaceholder": "Ex: Escalar equipe para 10 desenvolvedores, atingir breakeven financeiro...",
    "professionalDreamLabel": "Sonho Profissional (Sua Estrela Guia)",
    "professionalDreamPlaceholder": "Ex: Ser a maior referência de SaaS educacional do país, criar um negócio autossustentável...",
    "cancelBtnGeneral": "Cancelar",
    "saveBtnGeneral": "Salvar Alterações"
  },
  "toasts": {
    "triggerAde": "Acionando a ADE...",
    "triggerAdeDesc": "Aguarde enquanto sua Secretaria IA compila seu relatório de evolução.",
    "generated": "Relatório Gerado!",
    "generatedDesc": "A ADE estruturou seus próximos passos estratégicos.",
    "failed": "Falha na Geração",
    "nameRequired": "O Nome é obrigatório",
    "saveError": "Erro ao salvar perfil",
    "saveSuccess": "Perfil atualizado com sucesso!",
    "photoSuccess": "Foto de perfil enviada!",
    "photoError": "Erro no upload: {error}",
    "linkedinUrlRequired": "Informe a URL do seu LinkedIn primeiro!",
    "linkedinImportSuccess": "Dados importados do LinkedIn real com sucesso!",
    "linkedinImportError": "Erro ao importar: {error}"
  },
  "secretaryPanel": {
    "title": "Secretaria IA",
    "subtitle": "Inteligência Artificial e Mentor Diretor",
    "activateIntelTitle": "Acionar Inteligência da Secretaria",
    "activateIntelDesc": "A ADE compilará suas tarefas concluídas, sessões agendadas, diários de bordo e objetivos para gerar recomendações estratégicas exclusivas e apontar os seus próximos passos operacionais.",
    "activateBtnAnalyzing": "Analisando Performance...",
    "activateBtnGenerate": "Gerar Recomendações e Próximos Passos",
    "recommendationLabel": "Recomendação Estratégica Atual",
    "noRecTitle": "Nenhuma recomendação recente gerada.",
    "noRecDesc": "Clique no botão acima para ativar a ADE e obter insights acionáveis sobre sua evolução.",
    "historyTitle": "Histórico de Sugestões Anteriores",
    "suggestionFrom": "Sugestão de {date}",
    "closePanelBtn": "Fechar Painel"
  },
  "classes": {
    "techArch": "Arquiteto Tecnológico",
    "bizStrat": "Estrategista de Negócios",
    "highPerf": "Executor de Alta Performance",
    "multidisciplinary": "Analista Multidisciplinar",
    "operator": "Operador em Evolução"
  },
  "inventory": {
    "jack_1": { "name": "Jaqueta Corta-Vento Executive", "desc": "Design aerodinâmico cinza fosco." },
    "jack_2": { "name": "Sobretudo Italiano Lã", "desc": "Tecido estruturado elegante de lã natural." },
    "jack_3": { "name": "Trench Coat Clássico", "desc": "Corte alongado premium resistente à água." },
    "jack_4": { "name": "Blazer Minimalista Slim", "desc": "Corte descontraído cinza mescla em algodão nobre." },
    "jack_5": { "name": "Blazer Linho Rústico Noir", "desc": "Linho puro respirável com corte sob medida." },
    "jack_6": { "name": "Casaco Sob Medida Cashmere", "desc": "Cashmere italiano de ultra luxo feito por alfaiates." },
    "sneakers_1": { "name": "Sneaker Casual Couro", "desc": "Sola amortecedora e acabamento clássico." },
    "sneakers_2": { "name": "Sapato Derby Nobre", "desc": "Couro legítimo polido feito à mão." },
    "sneakers_3": { "name": "Mocassim Casual Camurça", "desc": "Conforto clássico para dias operacionais dinâmicos." },
    "sneakers_4": { "name": "Sapatênis Slip-on Knit", "desc": "Facilidade de calce e design elegante." },
    "back_1": { "name": "Mochila Slim Resistente", "desc": "Compacta, ideal for daily carry." },
    "back_2": { "name": "Pasta Executiva Minimalista", "desc": "Couro legítimo com divisórias acolchoadas premium." },
    "back_3": { "name": "Mochila Executiva Premium", "desc": "Compartimentos modulares inteligentes magnéticos." },
    "head_1": { "name": "Fone Noise-Canceling Matte", "desc": "Isolamento acústico eficiente para foco profundo." },
    "head_2": { "name": "Earbuds Invisíveis Premium", "desc": "Design ultra-discreto com drivers de alta fidelidade." },
    "head_3": { "name": "Headphone Estúdio Carbono", "desc": "Drivers profissionais de berílio com almofadas térmicas." },
    "watch_1": { "name": "Relógio Inteligente Stealth", "desc": "Monitoramento de produtividade e hábitos diários." },
    "watch_2": { "name": "Relógio Aço Safira Classic", "desc": "Vidro em cristal safira e caixa de aço escovado." },
    "watch_3": { "name": "Cronógrafo Híbrido Titânio", "desc": "Mostrador e-ink clássico de altíssimo prestígio." },
    "glass_1": { "name": "Óculos Anti-Fadiga Blue Light", "desc": "Proteção contra telas digitais e cansaço visual." },
    "glass_2": { "name": "Óculos Titanium Ultraleve", "desc": "Apenas 4 gramas, conforto invisível para longas horas." },
    "aura_1": { "name": "Sem Aura (Padrão)", "desc": "Aparência natural clássica e sem distorções." },
    "aura_2": { "name": "Brilho Âmbar de Produtividade", "desc": "Sutil pulsação dourada inspirada em foco total." },
    "aura_3": { "name": "Aura Focus Ciano", "desc": "Efeito suave que inspira estado de fluxo mental." },
    "aura_4": { "name": "Partículas Code Matrix", "desc": "Cascata minimalista digital de alta tecnologia." },
    "aura_5": { "name": "Espectro Prismático Executivo", "desc": "Efeito iridescente sutil exclusivo de alto escalão." }
  }
}

mentoring_profile_en = {
  "title": "My Mentoring Profile",
  "subtitleEdit": "Configuring Profile Details",
  "subtitleView": "Evolution and trajectory visualization",
  "levelPrefix": "LV",
  "xp": "XP",
  "noName": "No Name Defined",
  "roleMentor": "Mentor",
  "roleMentee": "Mentee",
  "noTagline": "Tagline not specified",
  "mentorExec": "Executive Mentor",
  "bizEstrategista": "Business Strategist",
  "specTooltipTitle": "Specialty",
  "specTooltipDesc": "Dynamically calculated from your goals, professional trajectory, and competencies.",
  "menteesCount": "Mentees: {count}",
  "levelLabel": "Level: {level}",
  "focusLabel": "Focus: {focus}",
  "focusTooltipTitle": "Focus Index",
  "focusTooltipDesc": "Daily focus metric (Mental Effort / Dedicated Time) calculated from your recent logbooks.",
  "tasksLabel": "Tasks: {completed}/{total}",
  "tasksTooltipTitle": "Tasks Executed",
  "tasksTooltipDesc": "Your progress on completed activities in the operational Kanban board.",
  "nextSession": "Next Session: {date}",
  "noSession": "No session scheduled",
  "publicLink": "Public Link",
  "motivationalQuotePlaceholder": "Define your tagline or quote in the profile configurations to display it here.",
  "achievements": {
    "consistent": {
      "title": "Consistent Focus",
      "desc": "More than 75% engagement in active tasks."
    },
    "implacavel": {
      "title": "Relentless",
      "desc": "Completed at least 5 tasks in the workspace."
    },
    "resiliente": {
      "title": "Resilient Operator",
      "desc": "Wrote your first report in the Logbook."
    },
    "visionario": {
      "title": "Visionary Leader",
      "desc": "Structured your future vision in the configurations."
    },
    "unlocked": "Unlocked",
    "locked": "Locked"
  },
  "social": {
    "linkedin": "LinkedIn",
    "github": "GitHub",
    "instagram": "Instagram",
    "website": "Website",
    "whatsapp": "WhatsApp"
  },
  "tabs": {
    "dashboard": "Evolution Dashboard",
    "diary": "Logbook",
    "tasks": "Tasks (Kanban)",
    "schedule": "Schedule Sessions",
    "mentorPanel": "Mentor Panel",
    "config": "Settings",
    "secretary": "AI Secretary"
  },
  "secReportHeader": "AI Secretary (I/O) • Evolution Report",
  "secReportSubtitle": "Strategic guidelines and operational next steps",
  "viewHistory": "View History",
  "reportTitle": "📄 Evolution Report",
  "createdAt": "Created at: {date}",
  "collapseReport": "↑ collapse report",
  "expandReport": "↓ click to expand complete report",
  "noReportGenerated": "No evolution report generated for this cycle.",
  "compiling": "Compiling...",
  "generateReport": "Generate Evolution Report",
  "guideTitle": "Guidelines & Evolution Alignment",
  "guideSubtitle": "Your personal strategic planning and purpose alignment in mentoring",
  "expectationLabel": "Mentoring Expectations",
  "notFilled": "Not filled in settings.",
  "shortTermLabel": "Short-Term Goals",
  "mediumTermLabel": "Medium-Term Goals",
  "professionalDreamLabel": "Professional Dream (Guiding Star)",
  "hobbiesLabel": "Hobbies, Arts & Talents",
  "bioTrajectoryLabel": "Biography & Trajectory",
  "noBio": "No biography available.",
  "experienceLabel": "Professional Experience",
  "noExperience": "Professional experience history not filled.",
  "skillsLabel": "Skills & Competencies",
  "noSkills": "No competencies listed.",
  "personalGoalLabel": "Personal Goal",
  "notDefined": "Not defined.",
  "careerGoalLabel": "Career Goal",
  "personalAttributesLabel": "3 Personal Attributes",
  "notFilledShort": "Not filled",
  "greatestAchievementsLabel": "3 Great Achievements",
  "greatestQualityLabel": "Greatest Quality",
  "howOthersSeeMe": "How others see me",
  "greatestQualityPlaceholder": "Not specified",
  "diary": {
    "newEntry": "New Diary Entry",
    "xpNote": "Log your cognitive metrics and daily learnings (+200 XP)",
    "mentalEffort": "Mental Effort / Focus: {cc} / 10",
    "ccTranquil": "Tranquil",
    "ccOverload": "Overload",
    "timeDedicated": "Time Dedicated / Focus: {te} / 10",
    "teFast": "Very Fast",
    "teSlow": "Time Consuming",
    "realProgress": "Real Progress: {progress}%",
    "progressStopped": "Stopped",
    "progressCompleted": "100% Completed",
    "notesLabel": "Notes & Learnings Report",
    "notesPlaceholder": "What were your challenges today? What did you learn or accomplish?",
    "formulaTension": "Tension Formula: TC = CC / TE | Distortion Formula: D = TC / (Progress %)",
    "writeNotesWarning": "Write something in the notes before registering your {termDiary}!",
    "registerEntry": "Register Entry",
    "diaryRegistered": "{termDiary} logged! +{xp} XP received!",
    "historyTitle": "Diary History",
    "historySubtitle": "Track your daily load and cognitive distortions",
    "noEntriesYet": "No notes registered so far.",
    "tensionLabel": "Tension",
    "distortionLabel": "Distortion",
    "flowHigh": "High Flow",
    "flowBalanced": "Balanced",
    "flowBurnoutRisk": "Burnout Risk"
  },
  "projects": {
    "title": "Professional Projects",
    "subtitle": "Showcase and manage your portfolios, startups and success cases in mentoring",
    "newProject": "New Project",
    "editProject": "Edit Project",
    "addProject": "Register New Project",
    "deleteConfirm": "Are you sure you want to delete this project?",
    "deletedSuccess": "Project deleted successfully!",
    "savedSuccess": "Project updated successfully!",
    "addedSuccess": "New project added successfully!",
    "featuredUpdated": "Project featured status updated successfully!",
    "removeFeatured": "Remove from Featured",
    "featurePublic": "Feature on Public Showcase",
    "uploadSuccess": "Project image uploaded successfully!",
    "uploadError": "Error uploading image",
    "projectTitleLabel": "Project Title",
    "projectTitlePlaceholder": "e.g., Telemedicine App, Finance MVP",
    "tagsLabel": "Tags / Technologies (comma separated)",
    "tagsPlaceholder": "e.g., NextJS, React Native, SaaS",
    "descLabel": "Detailed Description",
    "descPlaceholder": "Explain project goals, technology, and achieved results...",
    "imgLabel": "Case Image / Logo (URL or Upload)",
    "imgPlaceholder": "Paste the image URL or use the button on the right",
    "uploadBtn": "Upload File",
    "removeBtn": "Remove",
    "cancelBtn": "Cancel",
    "saveBtn": "Save Changes",
    "addBtn": "Add Project",
    "emptyTitle": "No projects registered",
    "emptySubtitle": "Register your main professional or study success cases",
    "addFirstProject": "Add First Project"
  },
  "mentorControls": {
    "nomenclaturasTitle": "Key Nomenclatures",
    "nomenclaturasSubtitle": "Personalize key terms used throughout the mentee's journey",
    "termDiaryLabel": "Logbook Term",
    "termTensionLabel": "Cognitive Tension Term",
    "termDistortionLabel": "Cognitive Distortion Term",
    "termSidequestLabel": "Side-quest Term",
    "algoXpTitle": "Algorithm & XP Settings",
    "algoXpSubtitle": "Adjust burnout thresholds and mentoring experience multipliers",
    "xpTaskLabel": "XP per Task: {value}",
    "xpDiaryLabel": "XP per Entry: {value}",
    "xpSessionLabel": "XP per Session: {value}",
    "burnoutLimitLabel": "Burnout Threshold: {value}",
    "templatesTitle": "Session Template Manager",
    "templatesSubtitle": "Add session templates and quick schedules for your students",
    "createNewTemplate": "Create New Template",
    "templateTitleLabel": "Session Title",
    "templateTitlePlaceholder": "e.g., Quarterly Planning",
    "templateDurationLabel": "Duration (Minutes)",
    "templateDescLabel": "Description/Focus",
    "templateDescPlaceholder": "Mentoring focus and topics to address...",
    "templateAddBtn": "Add Model",
    "templatesSavedTitle": "Saved Session Templates",
    "deleteTemplate": "Delete Template",
    "fillTemplateWarning": "Please fill in at least the template title!",
    "templateAddedToast": "Session template added!",
    "templateDeletedToast": "Session template deleted!"
  },
  "edit": {
    "realLinkedinImportTitle": "Real LinkedIn Importer",
    "realLinkedinImportDesc": "Automatically fill your biography and trajectories from your public LinkedIn",
    "realLinkedinBtn": "Import from Real LinkedIn",
    "realLinkedinConnecting": "Connecting...",
    "realLinkedinExtracting": "Extracting...",
    "realLinkedinPopulating": "Populating...",
    "realLinkedinImported": "Imported!",
    "cancelBtn": "Cancel",
    "cancelSuccessToast": "Import successfully cancelled.",
    "generalInfoTitle": "General Information",
    "roleLabel": "Role in Mentoring",
    "roleMentor": "Mentor",
    "roleMentee": "Mentee",
    "fullNameLabel": "Full Name",
    "fullNamePlaceholder": "Your name",
    "usernameLabel": "Username / Public Profile Slug",
    "usernamePlaceholder": "your-username",
    "usernameRules": "Lowercase letters, numbers and hyphens only. E.g. milton-bolonha",
    "photoLabel": "Profile Picture (Cloudinary Upload / URL)",
    "photoUploading": "Uploading...",
    "photoUploadBtn": "Upload",
    "taglineLabel": "Intro Tagline",
    "taglinePlaceholder": "e.g., CEO at 21 Miles | Upwork Developer",
    "genderLabel": "Gender Pronoun",
    "genderMaleOption": "Male (Mentee)",
    "genderFemaleOption": "Female (Mentee)",
    "genderNeutralOption": "Neutral (Mentee)",
    "linkedinLinkLabel": "LinkedIn Link",
    "motivationalLabel": "Motivational Quote",
    "motivationalPlaceholder": "A short sentence that inspires you...",
    "contactsTitle": "Contacts & Social Networks",
    "phoneLabel": "Phone Number",
    "phonePlaceholder": "e.g., +1 555-555-5555",
    "whatsappLabel": "WhatsApp (Clean Number)",
    "whatsappPlaceholder": "e.g., 5511999999999",
    "emailLabel": "Professional E-mail",
    "emailPlaceholder": "e.g., milton@21miles.com.br",
    "githubLabel": "GitHub Link",
    "instagramLabel": "Instagram Link",
    "websiteLabel": "Website / Portfolio Link",
    "mentorInfoTitle": "Mentor Information",
    "mentorBioLabel": "Professional Biography",
    "mentorBioPlaceholder": "Describe your journey, professional leadership and focus...",
    "mentorExperienceLabel": "Experience History / Career Achievements",
    "mentorExperiencePlaceholder": "What were your major roles, founded companies or time in market...",
    "skillsLabel": "Skills / Competencies",
    "skillsPlaceholder": "Add skill...",
    "addBtn": "Add",
    "clickToRemove": "Click to remove",
    "menteeInfoTitle": "Mentee Information",
    "personalGoalLabel": "Personal Goal",
    "personalGoalPlaceholder": "e.g., Greater emotional intelligence, family focus or balance...",
    "careerGoalLabel": "Career Goal",
    "careerGoalPlaceholder": "e.g., Career transition to Tech Leader, founding my own startup...",
    "personalAttributesLabel": "3 Outstanding personal attributes",
    "attributePlaceholder": "Attribute {num}",
    "experiencesLabel": "3 Life success experiences (General/Achievements)",
    "experiencePlaceholder": "Achievement {num}",
    "futureVisionLabel": "How you see yourself in the future (Medium/Long term vision)",
    "futureVisionPlaceholder": "Describe your dreams and where you see yourself in the next years...",
    "greatestAttributeLabel": "Greatest Attribute / Personal Quality",
    "greatestAttributePlaceholder": "If people could describe you in a single strong attribute, what would it be?",
    "familyGroupLabel": "Family Group (Describe briefly)",
    "familyGroupPlaceholder": "e.g., Married, 2 children, close relationship with parents...",
    "hobbiesLabel": "Hobbies, Talents & Artistic Skills",
    "hobbiesPlaceholder": "e.g., Digital painting, playing classical guitar, tennis...",
    "expectationsTitle": "Guidelines & Evolution Alignment",
    "expectationsSubtitle": "Define your strategic goals, dreams and professional alignment in mentoring",
    "expectationsLabel": "What you expect from mentoring (Expectations)",
    "expectationsPlaceholder": "e.g., Practical methodological alignment, candid feedback, strategic network...",
    "shortTermGoalsLabel": "Short-Term Goals (Immediate Focus)",
    "shortTermGoalsPlaceholder": "e.g., Complete the new platform MVP in 3 months, organize weekly schedule...",
    "mediumTermGoalsLabel": "Medium-Term Goals (Construction)",
    "mediumTermGoalsPlaceholder": "e.g., Scale team to 10 developers, reach financial breakeven...",
    "professionalDreamLabel": "Professional Dream (Your Guiding Star)",
    "professionalDreamPlaceholder": "e.g., Be the main SaaS educational reference in the country, create a self-sustaining business...",
    "cancelBtnGeneral": "Cancel",
    "saveBtnGeneral": "Save Changes"
  },
  "toasts": {
    "triggerAde": "Triggering ADE...",
    "triggerAdeDesc": "Please wait while your AI Secretary compiles your evolution report.",
    "generated": "Report Generated!",
    "generatedDesc": "ADE structured your next strategic steps.",
    "failed": "Generation Failed",
    "nameRequired": "Name is required",
    "saveError": "Error saving profile",
    "saveSuccess": "Profile updated successfully!",
    "photoSuccess": "Profile photo sent!",
    "photoError": "Upload error: {error}",
    "linkedinUrlRequired": "Please enter your LinkedIn URL first!",
    "linkedinImportSuccess": "Data successfully imported from real LinkedIn!",
    "linkedinImportError": "Import error: {error}"
  },
  "secretaryPanel": {
    "title": "AI Secretary",
    "subtitle": "Artificial Intelligence & Managing Mentor",
    "activateIntelTitle": "Trigger Secretary Intelligence",
    "activateIntelDesc": "ADE will compile your completed tasks, scheduled sessions, logbooks and objectives to generate exclusive strategic recommendations and point out your next operational steps.",
    "activateBtnAnalyzing": "Analyzing Performance...",
    "activateBtnGenerate": "Generate Recommendations & Next Steps",
    "recommendationLabel": "Current Strategic Recommendation",
    "noRecTitle": "No recent recommendations generated.",
    "noRecDesc": "Click the button above to activate ADE and get actionable insights on your evolution.",
    "historyTitle": "Previous Suggestions History",
    "suggestionFrom": "Suggestion from {date}",
    "closePanelBtn": "Close Panel"
  },
  "classes": {
    "techArch": "Technological Architect",
    "bizStrat": "Business Strategist",
    "highPerf": "High Performance Executor",
    "multidisciplinary": "Multidisciplinary Analyst",
    "operator": "Operator in Evolution"
  },
  "inventory": {
    "jack_1": { "name": "Executive Windbreaker Jacket", "desc": "Matte gray aerodynamic design." },
    "jack_2": { "name": "Wool Italian Overcoat", "desc": "Elegant structured fabric of natural wool." },
    "jack_3": { "name": "Classic Trench Coat", "desc": "Water-resistant premium elongated cut." },
    "jack_4": { "name": "Slim Minimalist Blazer", "desc": "Relaxed melange gray cut in noble cotton." },
    "jack_5": { "name": "Rustic Noir Linen Blazer", "desc": "Tailored pure breathable linen." },
    "jack_6": { "name": "Bespoke Cashmere Coat", "desc": "Ultra-luxury Italian cashmere made by tailors." },
    "sneakers_1": { "name": "Leather Casual Sneakers", "desc": "Shock-absorbing sole and classic finish." },
    "sneakers_2": { "name": "Noble Derby Shoes", "desc": "Handmade polished genuine leather." },
    "sneakers_3": { "name": "Suede Casual Loafers", "desc": "Classic comfort for dynamic operational days." },
    "sneakers_4": { "name": "Slip-on Knit Sapatênis", "desc": "Easy on and off and elegant design." },
    "back_1": { "name": "Slim Durable Backpack", "desc": "Compact, ideal for daily carry." },
    "back_2": { "name": "Minimalist Executive Briefcase", "desc": "Genuine leather with premium padded dividers." },
    "back_3": { "name": "Premium Executive Backpack", "desc": "Smart magnetic modular compartments." },
    "head_1": { "name": "Matte Noise-Canceling Headphones", "desc": "Efficient sound isolation for deep focus." },
    "head_2": { "name": "Premium Invisible Earbuds", "desc": "Ultra-discreet design with high-fidelity drivers." },
    "head_3": { "name": "Carbon Studio Headphones", "desc": "Professional beryllium drivers with thermal cushions." },
    "watch_1": { "name": "Stealth Smartwatch", "desc": "Productivity and daily habits monitoring." },
    "watch_2": { "name": "Sapphire Steel Classic Watch", "desc": "Sapphire crystal glass and brushed steel case." },
    "watch_3": { "name": "Titanium Hybrid Chronograph", "desc": "Classy high-prestige e-ink dial." },
    "glass_1": { "name": "Blue Light Anti-Fatigue Glasses", "desc": "Protection against digital screens and eye strain." },
    "glass_2": { "name": "Ultralight Titanium Glasses", "desc": "Only 4 grams, invisible comfort for long hours." },
    "aura_1": { "name": "No Aura (Default)", "desc": "Natural classic appearance without distortions." },
    "aura_2": { "name": "Productivity Amber Glow", "desc": "Subtle golden pulsation inspired by deep focus." },
    "aura_3": { "name": "Cyan Focus Aura", "desc": "Soft effect that inspires mental flow state." },
    "aura_4": { "name": "Code Matrix Particles", "desc": "Minimalist high-tech digital cascade." },
    "aura_5": { "name": "Executive Prismatic Spectrum", "desc": "Subtle iridescence effect exclusive for high ranks." }
  }
}

# Update pt.json
with open(pt_path, "r", encoding="utf-8") as f:
    pt_data = json.load(f)

if "admin" not in pt_data:
    pt_data["admin"] = {}
pt_data["admin"]["mentoringProfile"] = mentoring_profile_pt

with open(pt_path, "w", encoding="utf-8") as f:
    json.dump(pt_data, f, ensure_ascii=False, indent=2)

# Update en.json
with open(en_path, "r", encoding="utf-8") as f:
    en_data = json.load(f)

if "admin" not in en_data:
    en_data["admin"] = {}
en_data["admin"]["mentoringProfile"] = mentoring_profile_en

with open(en_path, "w", encoding="utf-8") as f:
    json.dump(en_data, f, ensure_ascii=False, indent=2)

print("SUCCESS")
