import { ObjectId } from "mongodb";
import { type Document } from "mongodb";
import { z } from "zod";
import type { Tile } from "@/lib/types";

// Schema Validator
export const bookContentSchema = z.object({
  id: z.string().optional(),
  title: z.string(),
  content: z.string(), // HTML generated by AI/edited by user
  sourceTileId: z.string().optional(), // Links back to the original Arc (Tile)
  orderIndex: z.number().default(0),
});

export const bookSchema = z.object({
  userId: z.string(),
  workspaceId: z.string(),
  dashboardId: z.string().optional(),
  title: z.string(),
  coverImageUrl: z.string().optional(),
  status: z.enum(["draft", "published"]).default("draft"),
  pages: z.array(bookContentSchema).default([]),
  
  // New Metadata Fields
  authorship: z.enum(["independent", "co-authorship"]).default("independent"),
  publisher: z.string().default("Autores Apaixonados"),
  isbn: z.string().optional(),
  isPublic: z.boolean().default(false),
  adultContent: z.boolean().default(false),
  restrictPublicity: z.boolean().default(false),
  pagesCountGoal: z.number().optional(),
  inspiration: z.string().default("Original"),
  removeCoAuthorship: z.boolean().default(false),
  generateCover: z.boolean().default(false),
  internalImagesCount: z.enum(["none", "1", "2", "3"]).default("none"),
  imageStyle: z.string().default("romantic"),
});

export type BookPage = z.infer<typeof bookContentSchema>;
export type Book = z.infer<typeof bookSchema>;

export interface BookDocument extends Document, Omit<Book, "id"> {
  _id?: ObjectId | string;
  createdAt: Date;
  updatedAt: Date;
}

export function bookToDocument(
  book: Book,
  userId: string,
  workspaceId: string,
  dashboardId?: string
): Omit<BookDocument, "_id" | "createdAt" | "updatedAt"> {
  return {
    userId,
    workspaceId,
    dashboardId,
    title: book.title,
    coverImageUrl: book.coverImageUrl,
    status: book.status,
    pages: book.pages,
    authorship: book.authorship,
    publisher: book.publisher,
    isbn: book.isbn,
    isPublic: book.isPublic,
    adultContent: book.adultContent,
    restrictPublicity: book.restrictPublicity,
    pagesCountGoal: book.pagesCountGoal,
    inspiration: book.inspiration,
    removeCoAuthorship: book.removeCoAuthorship,
    generateCover: book.generateCover,
    internalImagesCount: book.internalImagesCount,
    imageStyle: book.imageStyle,
  };
}
