import React, { useMemo } from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";

import { registerFonts } from "@/lib/pdf/fonts";

// Register standard fonts
registerFonts();

// Cover dimensions: 12.62 x 9.25 inches (908.88 x 666.047 points)
const styles = StyleSheet.create({
  page: {
    width: 908.88,
    height: 666.047,
    backgroundColor: "transparent",
    display: "flex",
    flexDirection: "row",
    padding: 0,
    margin: 0,
  },
  backCover: {
    width: "46%",
    height: "100%",
  },
  spine: {
    width: "8%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  frontCover: {
    width: "46%",
    height: "100%",
    position: "relative",
  },
  gradientOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "100%", // Full height to contain the steps
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
  },
  gradientStep1: { backgroundColor: 'rgba(0,0,0,0.5)', height: '8%' },
  gradientStep2: { backgroundColor: 'rgba(0,0,0,0.4)', height: '8%' },
  gradientStep3: { backgroundColor: 'rgba(0,0,0,0.3)', height: '8%' },
  gradientStep4: { backgroundColor: 'rgba(0,0,0,0.2)', height: '8%' },
  gradientStep5: { backgroundColor: 'rgba(0,0,0,0.1)', height: '8%' },
  gradientStep6: { backgroundColor: 'rgba(0,0,0,0.05)', height: '8%' },
  
  titleArea: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 40,
    paddingHorizontal: 20,
    zIndex: 10,
  },
  title: {
    fontSize: 36,
    fontFamily: "Oswald Bold",
    fontWeight: 700,
    color: "#FFFFFF",
    textAlign: "center",
    textTransform: "uppercase",
    lineHeight: 1.1,
    textShadow: '0 2px 4px rgba(0,0,0,0.5)',
  },
  author: {
    fontSize: 14,
    fontFamily: "Montserrat",
    fontWeight: 400,
    color: "#FFFFFF",
    textAlign: "center",
    letterSpacing: 4,
    marginTop: 10,
    textTransform: "uppercase",
  },
  spineTextContainer: {
    transform: "rotate(-90deg)",
    width: 666.047, // page height
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  spineText: {
    fontSize: 14,
    fontFamily: "Oswald Bold",
    fontWeight: 700,
    color: "#FFFFFF",
    textTransform: "uppercase",
    letterSpacing: 2,
  },
});

interface BookCoverDocumentProps {
  title: string;
  author: string;
  description: string;
  coverImageUrl?: string;
  pageCount: number;
  /** Main couple character names for personalized cover */
  coupleNames?: {
    character1: string;
    character2: string;
  };
}

/**
 * BookCoverDocument generates a professional book cover PDF
 *
 * LAYOUT EXPLANATION:
 * This component creates a full book cover with THREE sections:
 *
 * ┌─────────────────────────────────────────┐
 * │ VERSO (BACK) │ LOMBADA │  CAPA (FRONT)  │
 * │   36% width  │  8% var │   56% width    │
 * │ 152.4×228.6mm│variable │ 152.4×228.6mm  │
 * └─────────────────────────────────────────┘
 *
 * FULL COVER DIMENSIONS: 12.62 × 9.25 inches (908.88 × 666.047 points)
 *
 * RIGHT SIDE (FRONT COVER - 56%):
 * - Main hero image (generated by DALL-E 3 with full character context)
 * - Shows the couple/characters in intimate, emotionally-charged moment
 * - Title positioned at bottom
 * - Author name at bottom
 * - This is what people see on a bookshelf
 *
 * LEFT SIDE (BACK COVER - 36%):
 * - Blurb/Description
 * - Author bio
 * - ISBN barcode area
 * - Publisher info
 *
 * CENTER (SPINE - 8%, variable width):
 * - Book title (abbreviated if needed)
 * - Author surname
 * - Width varies based on page count:
 *   • 25 pages: ~1.43mm
 *   • 75 pages: ~4.29mm
 *   • 120 pages: ~6.86mm
 *
 * DALL-E 3 INTEGRATION:
 * The cover image is generated with FULL CONTEXT from dashboard:
 * - Character names, descriptions, personality traits
 * - Physical descriptions and age
 * - Book title, synopsis, and theme
 * - Romantic tone and emotional mood keywords
 * - Specific image style preference
 * - Complete story context for accurate, personalized imagery
 */
/**
 * Helper to wrap image URLs in our proxy to bypass CSP/CORS
 */
const getProxyUrl = (url: string) => {
  if (!url || url.startsWith("data:") || url.startsWith("/")) return url;
  return `/api/proxy-image?url=${encodeURIComponent(url)}`;
};

export function BookCoverDocument({
  title,
  author,
  description,
  coverImageUrl,
  pageCount,
  coupleNames,
}: BookCoverDocumentProps) {
  const spineWidthMm = useMemo(() => {
    // Calculate spine width based on page count
    if (pageCount <= 25) return 1.43;
    if (pageCount <= 75) return 4.29;
    return 6.86;
  }, [pageCount]);

  return (
    <Document title={`${title} - Book Cover`}>
      <Page size={[908.88, 666.047]} style={styles.page}>
        {/* Full Wrap Background Image */}
        {coverImageUrl && (
          <Image 
            src={getProxyUrl(coverImageUrl)} 
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: '100%',
              height: '100%',
              objectFit: 'cover',
            }} 
          />
        )}

        {/* Back Cover - Pure Imagery */}
        <View style={styles.backCover} />

        {/* Spine Overlay */}
        <View style={styles.spine}>
          <View style={styles.spineTextContainer}>
            <Text style={styles.spineText}>
              {title.length > 40 ? title.substring(0, 37) + "..." : title}
            </Text>
          </View>
        </View>

        {/* Front Cover Overlay */}
        <View style={styles.frontCover}>
          <View style={styles.gradientOverlay}>
            <View style={styles.gradientStep6} />
            <View style={styles.gradientStep5} />
            <View style={styles.gradientStep4} />
            <View style={styles.gradientStep3} />
            <View style={styles.gradientStep2} />
            <View style={styles.gradientStep1} />
          </View>
          <View style={styles.titleArea}>
            <Text style={styles.title}>{title}</Text>
            <Text style={styles.author}>By {author}</Text>
          </View>
        </View>
      </Page>
    </Document>
  );
}
