import React, { useMemo } from "react";
import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Font,
  Image,
} from "@react-pdf/renderer";

// Register standard fonts
Font.register({
  family: "Montserrat",
  fonts: [
    { src: "/fonts/Montserrat-Regular.ttf", fontWeight: 400 },
    { src: "/fonts/Montserrat-Bold.ttf", fontWeight: 700 },
  ],
});

Font.register({
  family: "Oswald Bold",
  fonts: [{ src: "/fonts/Oswald-Bold.otf", fontWeight: 700 }],
});

// Cover dimensions: 12.62 x 9.25 inches (908.88 x 666.047 points)
const styles = StyleSheet.create({
  page: {
    width: 908.88,
    height: 666.047,
    backgroundColor: "#FFFFFF",
    display: "flex",
    flexDirection: "row",
  },
  backCover: {
    width: "36%",
    backgroundColor: "#f3e5f5",
    padding: 20,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  spine: {
    width: "8%",
    backgroundColor: "#e1bee7",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  frontCover: {
    width: "56%",
    backgroundColor: "#ffffff",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: 30,
  },
  frontCoverImage: {
    width: "100%",
    height: "65%",
    objectFit: "cover",
    marginBottom: 20,
  },
  titleArea: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontFamily: "Oswald Bold",
    fontWeight: 700,
    color: "#1a1a1a",
    marginBottom: 10,
  },
  author: {
    fontSize: 12,
    fontFamily: "Montserrat",
    fontWeight: 400,
    color: "#666666",
  },
  backTitle: {
    fontSize: 18,
    fontFamily: "Oswald Bold",
    fontWeight: 700,
    color: "#1a1a1a",
    marginBottom: 12,
  },
  backDescription: {
    fontSize: 10,
    fontFamily: "Montserrat",
    fontWeight: 400,
    color: "#333333",
    lineHeight: 1.6,
    marginBottom: 20,
  },
  backAuthor: {
    fontSize: 11,
    fontFamily: "Montserrat",
    fontWeight: 700,
    color: "#1a1a1a",
  },
  barcode: {
    width: 60,
    height: 30,
    marginTop: 15,
    backgroundColor: "#f0f0f0",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#cccccc",
  },
  barcodeText: {
    fontSize: 8,
    color: "#666666",
  },
});

interface BookCoverDocumentProps {
  title: string;
  author: string;
  description: string;
  coverImageUrl?: string;
  pageCount: number;
  /** Main couple character names for personalized cover */
  coupleNames?: {
    character1: string;
    character2: string;
  };
}

/**
 * BookCoverDocument generates a professional book cover PDF
 *
 * LAYOUT EXPLANATION:
 * This component creates a full book cover with THREE sections:
 *
 * ┌─────────────────────────────────────────┐
 * │ VERSO (BACK) │ LOMBADA │  CAPA (FRONT)  │
 * │   36% width  │  8% var │   56% width    │
 * │ 152.4×228.6mm│variable │ 152.4×228.6mm  │
 * └─────────────────────────────────────────┘
 *
 * FULL COVER DIMENSIONS: 12.62 × 9.25 inches (908.88 × 666.047 points)
 *
 * RIGHT SIDE (FRONT COVER - 56%):
 * - Main hero image (generated by DALL-E 3 with full character context)
 * - Shows the couple/characters in intimate, emotionally-charged moment
 * - Title positioned at bottom
 * - Author name at bottom
 * - This is what people see on a bookshelf
 *
 * LEFT SIDE (BACK COVER - 36%):
 * - Blurb/Description
 * - Author bio
 * - ISBN barcode area
 * - Publisher info
 *
 * CENTER (SPINE - 8%, variable width):
 * - Book title (abbreviated if needed)
 * - Author surname
 * - Width varies based on page count:
 *   • 25 pages: ~1.43mm
 *   • 75 pages: ~4.29mm
 *   • 120 pages: ~6.86mm
 *
 * DALL-E 3 INTEGRATION:
 * The cover image is generated with FULL CONTEXT from dashboard:
 * - Character names, descriptions, personality traits
 * - Physical descriptions and age
 * - Book title, synopsis, and theme
 * - Romantic tone and emotional mood keywords
 * - Specific image style preference
 * - Complete story context for accurate, personalized imagery
 */
export function BookCoverDocument({
  title,
  author,
  description,
  coverImageUrl,
  pageCount,
  coupleNames,
}: BookCoverDocumentProps) {
  const spineWidthMm = useMemo(() => {
    // Calculate spine width based on page count
    if (pageCount <= 25) return 1.43;
    if (pageCount <= 75) return 4.29;
    return 6.86;
  }, [pageCount]);

  return (
    <Document title={`${title} - Book Cover`}>
      <Page size={[908.88, 666.047]} style={styles.page}>
        {/* Back Cover */}
        <View style={styles.backCover}>
          <View>
            <Text style={styles.backTitle}>{title}</Text>
            <Text style={styles.backDescription}>{description}</Text>
          </View>
          <View>
            <Text style={styles.backAuthor}>By {author}</Text>
            <View style={styles.barcode}>
              <Text style={styles.barcodeText}>ISBN</Text>
            </View>
          </View>
        </View>

        {/* Spine */}
        <View style={styles.spine}>
          <Text style={styles.author}>{title.substring(0, 5)}</Text>
        </View>

        {/* Front Cover */}
        <View style={styles.frontCover}>
          {coverImageUrl && (
            <Image src={coverImageUrl} style={styles.frontCoverImage} />
          )}
          <View style={styles.titleArea}>
            <Text style={styles.title}>{title}</Text>
            <Text style={styles.author}>By {author}</Text>
          </View>
        </View>
      </Page>
    </Document>
  );
}
